apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  forward("/wobserver", Wobserver.Web.Router)
  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
    pipe_through(:api)

    get("/supply", SupplyController, :supply)
  end

  scope "/api", BlockScoutWeb.API.RPC do
    pipe_through(:api)

    alias BlockScoutWeb.API.RPC

    forward("/", RPCTranslator, %{
      "block" => RPC.BlockController,
      "account" => RPC.AddressController,
      "logs" => RPC.LogsController,
      "token" => RPC.TokenController,
      "stats" => RPC.StatsController,
      "contract" => RPC.ContractController,
      "transaction" => RPC.TransactionController
    })
  end

  # Needs to be 200 to support the schema introspection for graphiql
  @max_complexity 200

  forward("/graphql", Absinthe.Plug,
    schema: BlockScoutWeb.Schema,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  forward("/graphiql", Absinthe.Plug.GraphiQL,
    schema: BlockScoutWeb.Schema,
    interface: :playground,
    socket: BlockScoutWeb.UserSocket,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  scope "/", BlockScoutWeb do
    pipe_through(:browser)

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources "/blocks", BlockController, only: [:index, :show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    resources("/pending_transactions", PendingTransactionController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal_transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token_transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal_transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new, :create],
        as: :verify_contract
      )

      resources(
        "/read_contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token_transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token_balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token_transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read_contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token_holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )
    end

    resources(
      "/smart_contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/search", ChainController, :search)

    get("/api_docs", APIDocsController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
defmodule BlockScoutWeb.AddressController do
  use BlockScoutWeb, :controller

  alias Explorer.{Chain, Market}
  alias Explorer.Chain.Address
  alias Explorer.ExchangeRates.Token

  def index(conn, _params) do
    render(conn, "index.html",
      address_tx_count_pairs: Chain.list_top_addresses(),
      address_estimated_count: Chain.address_estimated_count(),
      exchange_rate: Market.get_exchange_rate(Explorer.coin()) || Token.null(),
      total_supply: Chain.total_supply()
    )
  end

  def show(conn, %{"id" => id}) do
    redirect(conn, to: address_transaction_path(conn, :index, id))
  end

  def transaction_count(%Address{} = address) do
    Chain.total_transactions_sent_by_address(address)
  end

  def validation_count(%Address{} = address) do
    Chain.address_to_validation_count(address)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
defmodule BlockScoutWeb.API.RPC.AddressController do
  use BlockScoutWeb, :controller

  alias Explorer.{Chain, Etherscan}
  alias Explorer.Chain.{Address, Wei}

  def balance(conn, params, template \\ :balance) do
    with {:address_param, {:ok, address_param}} <- fetch_address(params),
         {:format, {:ok, address_hashes}} <- to_address_hashes(address_param) do
      addresses = hashes_to_addresses(address_hashes)
      render(conn, template, %{addresses: addresses})
    else
      {:address_param, :error} ->
        conn
        |> put_status(200)
        |> render(:error, error: "Query parameter 'address' is required")

      {:format, :error} ->
        conn
        |> put_status(200)
        |> render(:error, error: "Invalid address hash")
    end
  end

  def balancemulti(conn, params) do
    balance(conn, params, :balancemulti)
  end

  def txlist(conn, params) do
    options = optional_params(params)

    with {:address_param, {:ok, address_param}} <- fetch_address(params),
         {:format, {:ok, address_hash}} <- to_address_hash(address_param),
         {:ok, transactions} <- list_transactions(address_hash, options) do
      render(conn, :txlist, %{transactions: transactions})
    else
      {:address_param, :error} ->
        conn
        |> put_status(200)
        |> render(:error, error: "Query parameter 'address' is required")

      {:format, :error} ->
        conn
        |> put_status(200)
        |> render(:error, error: "Invalid address format")

      {:error, :not_found} ->
        render(conn, :error, error: "No transactions found", data: [])
    end
  end

  def txlistinternal(conn, params) do
    case {Map.fetch(params, "txhash"), Map.fetch(params, "address")} do
      {:error, :error} ->
        render(conn, :error, error: "Query parameter txhash or address is required")

      {{:ok, txhash_param}, :error} ->
        txlistinternal(conn, txhash_param, :txhash)

      {:error, {:ok, address_param}} ->
        txlistinternal(conn, params, address_param, :address)
    end
  end

  def txlistinternal(conn, txhash_param, :txhash) do
    with {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param),
         {:ok, internal_transactions} <- list_internal_transactions(transaction_hash) do
      render(conn, :txlistinternal, %{internal_transactions: internal_transactions})
    else
      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")

      {:error, :not_found} ->
        render(conn, :error, error: "No internal transactions found", data: [])
    end
  end

  def txlistinternal(conn, params, address_param, :address) do
    options = optional_params(params)

    with {:format, {:ok, address_hash}} <- to_address_hash(address_param),
         {:ok, internal_transactions} <- list_internal_transactions(address_hash, options) do
      render(conn, :txlistinternal, %{internal_transactions: internal_transactions})
    else
      {:format, :error} ->
        render(conn, :error, error: "Invalid address format")

      {:error, :not_found} ->
        render(conn, :error, error: "No internal transactions found", data: [])
    end
  end

  def tokentx(conn, params) do
    options = optional_params(params)

    with {:address_param, {:ok, address_param}} <- fetch_address(params),
         {:format, {:ok, address_hash}} <- to_address_hash(address_param),
         {:contract_address, {:ok, contract_address_hash}} <- to_contract_address_hash(params["contractaddress"]),
         {:ok, token_transfers} <- list_token_transfers(address_hash, contract_address_hash, options) do
      render(conn, :tokentx, %{token_transfers: token_transfers})
    else
      {:address_param, :error} ->
        render(conn, :error, error: "Query parameter address is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid address format")

      {:contract_address, :error} ->
        render(conn, :error, error: "Invalid contractaddress format")

      {:error, :not_found} ->
        render(conn, :error, error: "No token transfers found", data: [])
    end
  end

  @tokenbalance_required_params ~w(contractaddress address)

  def tokenbalance(conn, params) do
    with {:required_params, {:ok, fetched_params}} <- fetch_required_params(params, @tokenbalance_required_params),
         {:format, {:ok, validated_params}} <- to_valid_format(fetched_params, :tokenbalance) do
      token_balance = get_token_balance(validated_params)
      render(conn, "tokenbalance.json", %{token_balance: token_balance})
    else
      {:required_params, {:error, missing_params}} ->
        error = "Required query parameters missing: #{Enum.join(missing_params, ", ")}"
        render(conn, :error, error: error)

      {:format, {:error, param}} ->
        render(conn, :error, error: "Invalid #{param} format")
    end
  end

  def tokenlist(conn, params) do
    with {:address_param, {:ok, address_param}} <- fetch_address(params),
         {:format, {:ok, address_hash}} <- to_address_hash(address_param),
         {:ok, token_list} <- list_tokens(address_hash) do
      render(conn, :token_list, %{token_list: token_list})
    else
      {:address_param, :error} ->
        render(conn, :error, error: "Query parameter address is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid address format")

      {:error, :not_found} ->
        render(conn, :error, error: "No tokens found", data: [])
    end
  end

  def getminedblocks(conn, params) do
    options = put_pagination_options(%{}, params)

    with {:address_param, {:ok, address_param}} <- fetch_address(params),
         {:format, {:ok, address_hash}} <- to_address_hash(address_param),
         {:ok, blocks} <- list_blocks(address_hash, options) do
      render(conn, :getminedblocks, %{blocks: blocks})
    else
      {:address_param, :error} ->
        render(conn, :error, error: "Query parameter 'address' is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid address format")

      {:error, :not_found} ->
        render(conn, :error, error: "No blocks found", data: [])
    end
  end

  @doc """
  Sanitizes optional params.

  """
  @spec optional_params(map()) :: map()
  def optional_params(params) do
    %{}
    |> put_order_by_direction(params)
    |> put_pagination_options(params)
    |> put_start_block(params)
    |> put_end_block(params)
    |> put_filter_by(params)
    |> put_start_timestamp(params)
    |> put_end_timestamp(params)
  end

  @doc """
  Fetches required params. Returns error tuple if required params are missing.

  """
  @spec fetch_required_params(map(), list()) :: {:required_params, {:ok, map()} | {:error, [String.t(), ...]}}
  def fetch_required_params(params, required_params) do
    fetched_params = Map.take(params, required_params)

    result =
      if all_of_required_keys_found?(fetched_params, required_params) do
        {:ok, fetched_params}
      else
        missing_params = get_missing_required_params(fetched_params, required_params)
        {:error, missing_params}
      end

    {:required_params, result}
  end

  defp to_valid_format(params, :tokenbalance) do
    result =
      with {:ok, contract_address_hash} <- to_address_hash(params, "contractaddress"),
           {:ok, address_hash} <- to_address_hash(params, "address") do
        {:ok, %{contract_address_hash: contract_address_hash, address_hash: address_hash}}
      else
        {:error, _param_key} = error -> error
      end

    {:format, result}
  end

  defp all_of_required_keys_found?(fetched_params, required_params) do
    Enum.all?(required_params, &Map.has_key?(fetched_params, &1))
  end

  defp get_missing_required_params(fetched_params, required_params) do
    fetched_keys = fetched_params |> Map.keys() |> MapSet.new()

    required_params
    |> MapSet.new()
    |> MapSet.difference(fetched_keys)
    |> MapSet.to_list()
  end

  defp fetch_address(params) do
    {:address_param, Map.fetch(params, "address")}
  end

  defp to_address_hashes(address_param) when is_binary(address_param) do
    address_param
    |> String.split(",")
    |> Enum.take(20)
    |> to_address_hashes()
  end

  defp to_address_hashes(address_param) when is_list(address_param) do
    address_hashes = address_param_to_address_hashes(address_param)

    if any_errors?(address_hashes) do
      {:format, :error}
    else
      {:format, {:ok, address_hashes}}
    end
  end

  defp address_param_to_address_hashes(address_param) do
    Enum.map(address_param, fn single_address ->
      case Chain.string_to_address_hash(single_address) do
        {:ok, address_hash} -> address_hash
        :error -> :error
      end
    end)
  end

  defp any_errors?(address_hashes) do
    Enum.any?(address_hashes, &(&1 == :error))
  end

  defp hashes_to_addresses(address_hashes) do
    address_hashes
    |> Chain.hashes_to_addresses()
    |> add_not_found_addresses(address_hashes)
  end

  defp add_not_found_addresses(addresses, hashes) do
    found_hashes = MapSet.new(addresses, & &1.hash)

    hashes
    |> MapSet.new()
    |> MapSet.difference(found_hashes)
    |> hashes_to_addresses(:not_found)
    |> Enum.concat(addresses)
  end

  defp hashes_to_addresses(hashes, :not_found) do
    Enum.map(hashes, fn hash ->
      %Address{
        hash: hash,
        fetched_coin_balance: %Wei{value: 0}
      }
    end)
  end

  defp to_contract_address_hash(nil), do: {:contract_address, {:ok, nil}}

  defp to_contract_address_hash(address_hash_string) do
    {:contract_address, Chain.string_to_address_hash(address_hash_string)}
  end

  defp to_address_hash(address_hash_string) do
    {:format, Chain.string_to_address_hash(address_hash_string)}
  end

  defp to_address_hash(params, param_key) do
    case Chain.string_to_address_hash(params[param_key]) do
      {:ok, address_hash} -> {:ok, address_hash}
      :error -> {:error, param_key}
    end
  end

  defp to_transaction_hash(transaction_hash_string) do

apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
<div class="card card-primary" data-test="outside_of_dropdown">
  <div class="card-body">
    <h2 class="card-title text-white"><%= gettext "Balance" %></h2>
    <span></span>
    <div class="text-right">
      <h3 class="text-white" data-test="address_balance"><%= balance(@address) %></h3>
      <span class="text-white text-faded">
        <span
          data-wei-value="<%= if @address.fetched_coin_balance, do: @address.fetched_coin_balance.value %>"
          data-usd-exchange-rate="<%= @exchange_rate.usd_value %>">
        </span>
        <small>(@ <span data-usd-unit-price="<%= @exchange_rate.usd_value %>"></span>/<%= gettext("Ether") %>)</small>
      </span>

      <div class="mt-3" data-token-balance-dropdown data-api_path="<%= address_token_balance_path(BlockScoutWeb.Endpoint, :index, @address.hash) %>">
          <div data-loading class="mb-0 text-white text-faded">
            <span class="loading-spinner-small mr-2">
              <span class="loading-spinner-block-1"></span>
              <span class="loading-spinner-block-2"></span>
            </span>
            <%= gettext("Fetching tokens...") %>
          </div>

          <div data-error-message class="mb-0 text-white text-faded" style="display: none;">
            <%= gettext("Error trying to fetch balances.") %>
          </div>
      </div>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
<%= if @address do %>
  <%= link to: address_path(BlockScoutWeb.Endpoint, :show, @address), "data-test": "address_hash_link", class: assigns[:class] do %>
    <%= render BlockScoutWeb.AddressView, "_responsive_hash.html", address: @address, contract: @contract, truncate: assigns[:truncate] %>
  <% end %>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/address/_metatags.html.eex
<%= if assigns[:address] do %>
  <title>
    <%= gettext(
          "%{address} - %{subnetwork} Explorer",
          address: BlockScoutWeb.AddressView.address_page_title(@address),
          subnetwork: LayoutView.subnetwork_title()
        ) %>
  </title>
  <meta name="description" content="<%= gettext "View the account balance, transactions, and other data for %{address} on the %{network}", address: to_string(@address), network: LayoutView.network_title() %>">
  <meta name="keywords" content="<%= BlockScoutWeb.AddressView.address_page_title(@address) <> ", " <> Explorer.coin() <> ", "<> LayoutView.network_title() %>">
<% else %>
  <title>
    <%= gettext "Top Accounts - %{subnetwork} Explorer", subnetwork: LayoutView.subnetwork_title() %>
  </title>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
<span class="<%= if @contract do %>contract-address<% end %>" data-address-hash="<%= @address.hash %>">
  <%= if name = primary_name(@address) do %>
    <span data-toggle="tooltip" data-placement="top" title="<%= @address.hash %>"><%= name %> (<%= short_hash(@address) %>...)</span>
  <% else %>
    <%= if assigns[:truncate] do %>
      <%= BlockScoutWeb.AddressView.trimmed_hash(@address.hash) %>
    <% else %>
      <span class="d-none d-md-none d-lg-inline"><%= @address.hash %></span>
      <span class="d-md-inline-block d-lg-none"><%= BlockScoutWeb.AddressView.trimmed_hash(@address.hash) %></span>
    <% end %>
  <% end %>
</span>

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
<!-- DESKTOP TAB NAV -->
<ul class="nav nav-tabs card-header-tabs d-none d-lg-inline-flex">
   <li class="nav-item">
    <%= link(
          gettext("Tokens"),
          class: "nav-link #{tab_status("tokens", @conn.request_path)}",
          to: address_token_path(@conn, :index, @address.hash),
          "data-test": "tokens_tab_link"
        ) %>
  </li>

   <%= if BlockScoutWeb.AddressView.validator?(@validation_count) do %>
    <li class="nav-item">
      <%= link(
        gettext("Blocks Validated"),
        class: "nav-link",
        "data-test": "validations_tab_link",
        to: address_validation_path(@conn, :index, @address.hash)
      ) %>
    </li>
  <% end %>

  <%= if contract?(@address) do %>
    <li class="nav-item">
      <%= link(
          to: address_contract_path(@conn, :index, @address.hash),
          class: "nav-link #{tab_status("contracts", @conn.request_path)}") do %>
          <%= gettext("Code") %>

        <%= if smart_contract_verified?(@address) do %>
          <i class="far fa-check-circle text-success"></i>
        <% end %>
      <% end %>
    </li>
  <% end %>

  <%= if smart_contract_with_read_only_functions?(@address) do %>
    <li class="nav-item">
      <%= link(
          gettext("Read Contract"),
          to: address_read_contract_path(@conn, :index, @address.hash),
          class: "nav-link #{tab_status("read_contract", @conn.request_path)}")%>
    </li>
  <% end %>
</ul>

<!-- MOBILE DROPDOWN NAV -->
<ul class="nav nav-tabs card-header-tabs d-lg-none">
  <li class="nav-item dropdown flex-fill text-center">
    <a class="nav-link active dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      <%= current_tab_name(@conn.request_path) %>
    </a>
    <div class="dropdown-menu">
      <%= link(
            gettext("Transactions"),
            class: "dropdown-item #{tab_status("transactions", @conn.request_path)}",
            to: address_transaction_path(@conn, :index, @address.hash)
          ) %>
      <%= link(
            gettext("Tokens"),
            class: "dropdown-item  #{tab_status("tokens", @conn.request_path)}",
            to: address_token_path(@conn, :index, @address.hash)
          ) %>
      <%= link(
            gettext("Internal Transactions"),
            class: "dropdown-item #{tab_status("internal_transactions", @conn.request_path)}",
            "data-test": "internal_transactions_tab_link",
            to: address_internal_transaction_path(@conn, :index, @address.hash)
          ) %>
      <%= if validator?(@validation_count) do %>
        <%= link(
          gettext("Blocks Validated"),
          class: "dropdown-item",
          "data-test": "validations_tab_link",
          to: address_validation_path(@conn, :index, @address.hash)
        ) %>
      <% end %>
      <%= if contract?(@address) do %>
        <%= link(
            to: address_contract_path(@conn, :index, @address.hash),
            class: "dropdown-item #{tab_status("contracts", @conn.request_path)}") do %>
          <%= gettext("Code") %>

          <%= if smart_contract_verified?(@address) do %>
            <i class="far fa-check-circle"></i>
          <% end %>
        <% end %>
      <% end %>
      <%= if smart_contract_with_read_only_functions?(@address) do %>
        <%= link(
            gettext("Read Contract"),
            to: address_read_contract_path(@conn, :index, @address.hash),
            class: "dropdown-item #{tab_status("read_contract", @conn.request_path)}")%>
      <% end %>
    </div>
  </li>
</ul>

apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
<section class="container">
  <div class="card">
    <div class="card-body">
      <h1><%= gettext "Addresses" %></h1>
      <p>
        <%= gettext "Showing 250 addresses of" %>
        <%= Cldr.Number.to_string!(@address_estimated_count, format: "#,###") %>
        <%= gettext "total addresses with a balance" %>
      </p>

      <span data-selector="top-addresses-list">
        <%= for {{address, tx_count}, index} <- Enum.with_index(@address_tx_count_pairs, 1) do %>
          <%= render "_tile.html", 
            address: address, index: index, exchange_rate: @exchange_rate,
            total_supply: @total_supply, tx_count: tx_count,
            validation_count: validation_count(address) %> 
        <% end %>
      </span>
    </div>
  </div>
</section>

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
<section class="address-overview" data-page="address-details" data-page-address-hash="<%= @address %>">
  <div class="row">
    <div class="card-section col-md-12 col-lg-8">
      <div class="card">
        <div class="card-body">
          <div class="icon-links float-right">
            <span data-clipboard-text="<%= @address %>">
              <button type="button" class="icon-link" id="button" data-toggle="tooltip" data-placement="top" title="<%= gettext("Copy Address") %>" aria-label="<%= gettext("Copy Address") %>">
                <i class="fas fa-clone"></i>
              </button>
            </span>
            <span data-toggle="modal" data-target="#qrModal">
              <button type="button" class="icon-link"  data-toggle="tooltip" data-placement="top" title="<%= gettext("QR Code") %>" aria-label="<%= gettext("Show QR Code") %>">
                <i class="fas fa-qrcode"></i>
              </button>
            </span>
          </div>
          <h1 class="card-title"><%= address_title(@address) %> <%= gettext "Details" %> </h1>
          <h3 class="<%= if BlockScoutWeb.AddressView.contract?(@address) do %>contract-address<% end %>" data-test="address_detail_hash"><%= @address.hash %></h3>
          <div class="d-flex flex-column flex-lg-row justify-content-start text-muted">
            <%= if address_name = primary_name(@address) do %>
              <strong class="mr-4 mb-2 text-primary"><%= address_name %></strong>
            <% end %>
            <%= if @address.token do %>
              <span class="mr-4 mb-2">
                <%= link(token_title(@address.token), to: token_path(@conn, :show, @address.hash), "data-test": "token_hash_link" ) %>
              </span>
            <% end %>
            <span class="mr-4 mb-2">
              <span data-selector="transaction-count">
                <%= Cldr.Number.to_string!(@transaction_count, format: "#,###") %>
              </span>
              <%= gettext("Transactions sent") %>
              <%= if validator?(@validation_count) do %>
                <span data-selector="validation-count">
                  <%= Cldr.Number.to_string!(@validation_count, format: "#,###") %>
                </span> <%= gettext("Blocks Validated") %>
              <% end %>
            </span>
          </div>
          <%= if contract?(@address) do %>
            <span class="text-muted" data-test="address_contract_creator">
              <%= gettext "Created by" %>
              <%= link(
                trimmed_hash(@address.contracts_creation_internal_transaction.from_address_hash),
                to: address_path(@conn, :show, @address.contracts_creation_internal_transaction.from_address_hash)
              ) %>

              <%= gettext "at" %>

              <%= link(
                trimmed_hash(@address.contracts_creation_internal_transaction.transaction_hash),
                to: transaction_path(@conn, :show, @address.contracts_creation_internal_transaction.transaction_hash),
                "data-test": "transaction_hash_link"
              ) %>
            </span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-section col-md-12 col-lg-4" data-selector="balance-card">
      <%= render BlockScoutWeb.AddressView, "_balance_card.html", conn: @conn, address: @address, exchange_rate: @exchange_rate %>
    </div>

  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="qrModal" tabindex="-1" role="dialog" aria-labelledby="qrModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="qrModalLabel"><%= gettext "QR Code" %></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="<%= gettext("Close") %>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="data:image/png;base64, <%= qr_code(@address) %>" class="qr-code" alt="qr_code" title="<%= @address %>" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><%= gettext "Close" %></button>
      </div>
    </div>
  </div>
</div>